In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('df_autonomus.csv')
df
col1=list(df.self_driving)
col1
binary=[]

In [3]:
for i in col1:
    if i=="Yes":
        binary.append(1)
    else:
        binary.append(0)
binary

[0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,


In [4]:
df['new']=binary
df.head(10)
df.columns

Index(['self_driving', 'safety_concern', 'carshare_level', 'rideshare_level',
       'pevowner', 'income', 'householdvehicles', 'housing', 'parkingtype',
       'new'],
      dtype='object')

In [5]:
resp=df['new']
import statsmodels.formula.api as smf
model = smf.logit(formula = 'new ~ safety_concern +carshare_level+ rideshare_level+pevowner+ income+ householdvehicles+ housing+ parkingtype', data = df).fit() 
model.summary()

Optimization terminated successfully.
         Current function value: 0.615207
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                    new   No. Observations:                 3614
Model:                          Logit   Df Residuals:                     3598
Method:                           MLE   Df Model:                           15
Date:                Sun, 20 Nov 2022   Pseudo R-squ.:                  0.1009
Time:                        19:49:00   Log-Likelihood:                -2223.4
converged:                       True   LL-Null:                       -2472.8
Covariance Type:            nonrobust   LLR p-value:                 9.765e-97
==================================================================================================================
                                                     coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
Intercept                                         -0.6738      0.201     -3.352      0.001      -1.068      -0.280
safety_concern[T.Disagree]                         0.9348      0.130      7.169      0.000       0.679       1.190
safety_concern[T.Neutral]                         -0.7997      0.183     -4.367      0.000      -1.159      -0.441
carshare_level[T.Interested in participating]     -1.1363      0.141     -8.064      0.000      -1.413      -0.860
carshare_level[T.Not participating]               -0.6290      0.086     -7.286      0.000      -0.798      -0.460
rideshare_level[T.Interested in participating]    -0.2853      0.108     -2.641      0.008      -0.497      -0.074
rideshare_level[T.Not participating]              -0.3080      0.090     -3.415      0.001      -0.485      -0.131
pevowner[T.Yes]                                   -0.7011      0.146     -4.794      0.000      -0.988      -0.414
income[T.Low income]                               0.3845      0.121      3.185      0.001       0.148       0.621
income[T.Middle income]                            0.3431      0.101      3.382      0.001       0.144       0.542
householdvehicles[T.Three plus]                    0.2899      0.108      2.674      0.007       0.077       0.502
householdvehicles[T.Two vehicle]                   0.0926      0.086      1.076      0.282      -0.076       0.261
housing[T.Mobile based home]                      -0.0124      0.277     -0.045      0.964      -0.556       0.531
housing[T.Others]                                  0.2625      0.580      0.453      0.651      -0.874       1.400
housing[T.Single family]                          -0.1062      0.116     -0.913      0.361      -0.334       0.122
parkingtype[T.Shared parking]                     -0.0326      0.114     -0.287      0.774      -0.255       0.190
==================================================================================================================
"""

INTERPRETATION
Since p value <=0.05 for safety_concern,carshare_level,rideshare_level,pevowner,income and householdvehicles(Three plus) so these independent variables are significant

#new model(discarding non significant values)


In [7]:
# For the following columns the influence on the 'new' column or self driving 
# will be zero or minimum since the values from 0.025 to 0.975 are changing
# from negative to positive.

#householdvehicles[T.Two vehicle] 
#housing[T.Mobile based home] 
#housing[T.Others]
#housing[T.Single family] 
#parkingtype[T.Shared parking] 

In [6]:
model1 = smf.logit(formula = 'new ~ safety_concern +carshare_level+ rideshare_level+pevowner+ income+ householdvehicles', data = df).fit()
model1.summary()

Optimization terminated successfully.
         Current function value: 0.615388
         Iterations 6


<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                    new   No. Observations:                 3614
Model:                          Logit   Df Residuals:                     3602
Method:                           MLE   Df Model:                           11
Date:                Sun, 20 Nov 2022   Pseudo R-squ.:                  0.1006
Time:                        19:49:03   Log-Likelihood:                -2224.0
converged:                       True   LL-Null:                       -2472.8
Covariance Type:            nonrobust   LLR p-value:                 1.058e-99
==================================================================================================================
                                                     coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
Intercept                                         -0.7517      0.173     -4.356      0.000      -1.090      -0.413
safety_concern[T.Disagree]                         0.9306      0.130      7.150      0.000       0.675       1.186
safety_concern[T.Neutral]                         -0.8031      0.183     -4.390      0.000      -1.162      -0.445
carshare_level[T.Interested in participating]     -1.1349      0.141     -8.061      0.000      -1.411      -0.859
carshare_level[T.Not participating]               -0.6282      0.086     -7.285      0.000      -0.797      -0.459
rideshare_level[T.Interested in participating]    -0.2828      0.108     -2.619      0.009      -0.494      -0.071
rideshare_level[T.Not participating]              -0.3056      0.090     -3.400      0.001      -0.482      -0.129
pevowner[T.Yes]                                   -0.7029      0.146     -4.808      0.000      -0.989      -0.416
income[T.Low income]                               0.3967      0.120      3.320      0.001       0.162       0.631
income[T.Middle income]                            0.3480      0.101      3.439      0.001       0.150       0.546
householdvehicles[T.Three plus]                    0.2634      0.105      2.511      0.012       0.058       0.469
householdvehicles[T.Two vehicle]                   0.0730      0.084      0.872      0.383      -0.091       0.237
==================================================================================================================
"""

#In this output, all independent variables are statistically significant and the signs are logical, so this model can be used for further diagnosis.

In [7]:
#calculating odds ratio
import numpy as np
conf = model1.conf_int()
conf['OR'] = model1.params
conf.columns = ['2.5%', '97.5%', 'OR']
print(np.exp(conf))

                                                    2.5%     97.5%        OR
Intercept                                       0.336222  0.661340  0.471548
safety_concern[T.Disagree]                      1.964963  3.272932  2.535979
safety_concern[T.Neutral]                       0.312969  0.641128  0.447943
carshare_level[T.Interested in participating]   0.243954  0.423611  0.321468
carshare_level[T.Not participating]             0.450588  0.631803  0.533556
rideshare_level[T.Interested in participating]  0.609923  0.931284  0.753666
rideshare_level[T.Not participating]            0.617666  0.878570  0.736657
pevowner[T.Yes]                                 0.371810  0.659434  0.495161
income[T.Low income]                            1.176418  1.879326  1.486901
income[T.Middle income]                         1.161440  1.727050  1.416286
householdvehicles[T.Three plus]                 1.059466  1.598391  1.301323
householdvehicles[T.Two vehicle]                0.912944  1.267628  1.075766

In [8]:
 #Predicting probabilities
 from sklearn.metrics import confusion_matrix
 predicted_values1 = model1.predict()
 threshold=0.5
 predicted_class1=np.zeros(predicted_values1.shape)
 predicted_class1[predicted_values1>threshold]=1
 cm1 = confusion_matrix(df['new'],predicted_class1)
 print('Confusion Matrix : \n', cm1) 

Confusion Matrix : 
 [[1514  534]
 [ 691  875]]


In [5]:
# From confusion matrix we can say that 1514 are correctly predicted 
# as not self_driving(True Negative) and 875 correctly predicted
# as self_driving (True Positive).

# 534 were predicted as self driving but all these were observed 
#as non-self driving.(False Positive)

# 691 instances were predicted as non-self driving
#but were self-driving(False Negative)





In [6]:
#From confusion matrix we can say that 1514 are correctly 
#predicted as not self_driving and 875 correctly predicted
#self_driving

#The precision and recall values of the model are routinely 
#assessed in a classification model. 

#Precision tells us what percentage of predicted positive cases
#are correctly predicted. 
#Recall tells us what percentage of actual positive cases are correctly predicted.

In [9]:
from sklearn.metrics import classification_report
print(classification_report(df['new'],predicted_class1))

              precision    recall  f1-score   support

           0       0.69      0.74      0.71      2048
           1       0.62      0.56      0.59      1566

    accuracy                           0.66      3614
   macro avg       0.65      0.65      0.65      3614
weighted avg       0.66      0.66      0.66      3614



In [4]:
# Accuracy=66%
# Precision is 62% and Recall is 56% for self driving affinity

In [3]:
#The precision and recall values of the model
#are routinely assessed in a classification model. 

#Precision tells us what percentage of predicted positive cases 
#are correctly predicted. 
#Recall tells us what percentage of actual positive cases are correctly predicted.

In [10]:
import numpy as np
import pandas as pd

In [11]:
df=pd.read_csv('df_autonomus.csv')
df
col1=list(df.self_driving)
col1

MNLogit=[]

In [12]:
for i in col1:
    if i=='Yes':
        MNLogit.append(1)
    elif i== 'Neutral':
        MNLogit.append(2)
    else:
        MNLogit.append(3)
MNLogit

[3,
 1,
 3,
 3,
 2,
 2,
 3,
 2,
 3,
 2,
 3,
 3,
 2,
 1,
 2,
 1,
 3,
 2,
 2,
 2,
 3,
 1,
 2,
 2,
 2,
 1,
 1,
 1,
 3,
 2,
 2,
 3,
 1,
 2,
 2,
 1,
 2,
 3,
 1,
 3,
 2,
 1,
 3,
 3,
 1,
 1,
 2,
 1,
 2,
 3,
 3,
 1,
 2,
 1,
 1,
 2,
 3,
 1,
 2,
 2,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 3,
 1,
 2,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 3,
 3,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 2,
 1,
 1,
 2,
 3,
 3,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 3,
 3,
 1,
 1,
 3,
 1,
 1,
 3,
 1,
 3,
 1,
 3,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 3,
 1,
 3,
 1,
 3,
 3,
 2,
 1,
 1,
 3,
 3,
 3,
 1,
 3,
 1,
 1,
 1,
 1,
 2,
 3,
 1,
 3,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 3,
 3,
 3,
 1,
 3,
 1,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 3,
 2,
 2,
 1,
 2,
 1,
 2,
 1,
 2,
 2,
 1,
 1,
 3,
 1,
 2,
 1,
 3,
 2,
 2,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 3,
 3,
 1,
 2,
 1,
 1,
 2,
 1,
 3,
 3,
 1,
 1,
 3,
 2,
 2,
 3,
 1,
 2,
 3,
 3,
 3,
 2,
 1,
 1,
 2,
 2,
 2,
 2,
 1,
 1,
 3,
 3,
 2,
 3,
 2,
 2,
 3,
 1,
 3,
 1,
 1,
 1,


In [13]:
df['MNLogit_new']=MNLogit
df.head(10)
df.columns

Index(['self_driving', 'safety_concern', 'carshare_level', 'rideshare_level',
       'pevowner', 'income', 'householdvehicles', 'housing', 'parkingtype',
       'MNLogit_new'],
      dtype='object')

In [15]:
from statsmodels.discrete.discrete_model import MNLogit
formula = 'MNLogit_new ~ safety_concern +carshare_level+ rideshare_level+pevowner+ income+ householdvehicles+ housing+ parkingtype'
model_MNL = MNLogit.from_formula(formula=formula , data = df ).fit()
print(model_MNL.summary())

Optimization terminated successfully.
         Current function value: 0.958242
         Iterations 6
                          MNLogit Regression Results                          
Dep. Variable:            MNLogit_new   No. Observations:                 3614
Model:                        MNLogit   Df Residuals:                     3582
Method:                           MLE   Df Model:                           30
Date:                Sun, 20 Nov 2022   Pseudo R-squ.:                 0.09351
Time:                        19:51:21   Log-Likelihood:                -3463.1
converged:                       True   LL-Null:                       -3820.3
Covariance Type:            nonrobust   LLR p-value:                4.721e-131
                                 MNLogit_new=2       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
Intercept                           

In [ ]:
# for both MNL =2 and MNL=3 tables some variables are not signiganct
# hence i would later be fitting a regression model between those parameters that
# matter

# The values ranging from negative to positive in 0.025 and 0.975
# have no or minimum effect on our response variable

# only safety_concern[T.Neutral] and carshare_level are significant when 
# compared to MNL_new = 1 for those who are taking neutral stand(MNL_new=2) in adoption of
# autonomous vehicles(P<0.05)

# Income[T.Low income] has odds ratio of e^-0.1716 = 0.8423 for MNL_new = 2
# and Income[T.Low income] has odds ratio of e^-0.5079 = 0.6017
# For both the values the lower income will reduce the odds for adoption 
# of autonomous vehicles because the odds ratio values are less than 1.

#householdvehicles[T.Two vehicle],housing[T.Mobile based home],housing[T.Others] 
#housing[T.Single family],parkingtype[T.Shared parking] are not significant
# with respect to People saying 'Yes' or MNL_new =1

In [16]:
model_MNL.params
np.exp(model_MNL.params)

0         1
Intercept                                       0.236390  1.711381
safety_concern[T.Disagree]                      1.235509  0.266433
safety_concern[T.Neutral]                       8.805343  1.220761
carshare_level[T.Interested in participating]   2.085759  3.766129
carshare_level[T.Not participating]             1.760378  1.952310
rideshare_level[T.Interested in participating]  1.053182  1.607932
rideshare_level[T.Not participating]            0.955638  1.734321
pevowner[T.Yes]                                 1.260941  2.434345
income[T.Low income]                            0.842348  0.601763
income[T.Middle income]                         0.858758  0.639910
householdvehicles[T.Three plus]                 0.761154  0.744734
householdvehicles[T.Two vehicle]                0.936783  0.900284
housing[T.Mobile based home]                    0.936711  1.036154
housing[T.Others]                               1.497748  0.195292
housing[T.Single family]                        1.268627  1.016157
parkingtype[T.Shared parking]                   1.257552  0.899802

In [17]:
#Marginal Effects
print(model_MNL.get_margeff().summary())

       MNLogit Marginal Effects      
Dep. Variable:            MNLogit_new
Method:                          dydx
At:                           overall
                                 MNLogit_new=1      dy/dx    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
safety_concern[T.Disagree]                         0.1533      0.029      5.204      0.000       0.096       0.211
safety_concern[T.Neutral]                         -0.2100      0.040     -5.243      0.000      -0.288      -0.131
carshare_level[T.Interested in participating]     -0.2339      0.029     -7.944      0.000      -0.292      -0.176
carshare_level[T.Not participating]               -0.1345      0.018     -7.488      0.000      -0.170      -0.099
rideshare_level[T.Interested in participating]    -0.0659      0.023     -2.855      0.004      -0.111      -0.021
rideshare_level[T.Not participating]       

In [18]:
MLE = model_MNL.llf
print("Maximum Likelihood Estimate = ", MLE)

Maximum Likelihood Estimate =  -3463.088240295422


In [19]:
p = 3
AIC_1 = - 2 * MLE + 2 * p
print("Akaike Information Criteria = ", AIC_1)

Akaike Information Criteria =  6932.176480590844


In [20]:
#c) Bayesian Information Criteria (AIC)
BIC = model_MNL.bic
print("BIC", BIC)

BIC 7188.338735667714


In [21]:
# prediction of probability
yprob = model_MNL.predict()
print(yprob)

def compute_yhat(prob):
    
    yhat = np.argmax(prob, axis=1)
    
    return yhat

ypred = compute_yhat(yprob)
ypred

[[0.47794928 0.2105058  0.31154493]
 [0.35980573 0.1877623  0.45243197]
 [0.27438853 0.46455712 0.26105434]
 ...
 [0.5383785  0.22953344 0.23208806]
 [0.66522622 0.20260384 0.13216994]
 [0.68352863 0.16554228 0.1509291 ]]


array([0, 2, 1, ..., 0, 0, 0], dtype=int64)

In [22]:
from sklearn.metrics import accuracy_score
Accuracy = accuracy_score(ypred, df.MNLogit_new)
Accuracy

0.06751521859435529

In [23]:
#some parameters are not significant and hence i am neglecting those 
#parameters and fitting a regression for those parameters that matter


In [24]:
from statsmodels.discrete.discrete_model import MNLogit
formula = 'MNLogit_new ~ safety_concern +carshare_level+ rideshare_level+pevowner+ income'
model_MNL = MNLogit.from_formula(formula=formula , data = df ).fit()
print(model_MNL.summary())

Optimization terminated successfully.
         Current function value: 0.960692
         Iterations 6
                          MNLogit Regression Results                          
Dep. Variable:            MNLogit_new   No. Observations:                 3614
Model:                        MNLogit   Df Residuals:                     3594
Method:                           MLE   Df Model:                           18
Date:                Sun, 20 Nov 2022   Pseudo R-squ.:                 0.09119
Time:                        19:51:54   Log-Likelihood:                -3471.9
converged:                       True   LL-Null:                       -3820.3
Covariance Type:            nonrobust   LLR p-value:                2.761e-136
                                 MNLogit_new=2       coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------------
Intercept                           

In [25]:
# coeff for income[T.Low income] = -0.1129 for MNL_new=2 or 'Neutral'
# odds ratio is e^-0.1129 = 0.89
# Compared to MNL=1 low income are less likely to show interest to 
#use autonomous vehicles by 1-0.89 =0.11

# coef for income[T.Low income] is -0.4571 for MNL_new =3 or 'No'
# odds ratio is e^-0.4571 = 0.6333
# odds ratio decreases by 1-0.6333 = 0.366 compared to MNL=1

# This means that lower income group members who say 'No' 
#show less affinity towards self autonomous by 36.6%


# coeff for Income[T.Middle income] = -0.1231
# odds ratio is e^-0.1231 = 0.8841 or 88.41%
# odds will decrease by 1-0.8841 = 0.1159 or by 11.59%

In [ ]:
# coeff for income[T.Low income] = -0.1129
# odds ratio is e^-0.1129 = 0.89

# Compared to MNL=1 low income are less likely to use autonomous 
# vehicles by 1-0.89 =0.11

# choice of selection of self driving autonomous vehicle(for neutral people) is 0.89 times 'Yes'
# or MNL_new = 1 

# coef for income[T.Low income] is -0.4571 for MNL_new =3 or 'No'
# odds ratio is e^-0.4571 = 0.6333
# odds ratio decreases by 1-0.6333 = 0.366 compared to MNL=1
# This means that lower income group members who say 'No' show less affinity towards self autonomous by 36.6%


# coeff for Income[T.Middle income] = -0.1231
# odds ratio is e^-0.1231 = 0.8841 or 88.41%
# odds will decrease by 1-0.8841 = 0.1159 or by 11.59%

# In general it seems like richer people are more likely to use
# self driving autonomous vehicles.

# The variables except safety_concern[T.Neutral] are all significant when
# compared with People who say 'Yes' in MNLogit_new =1 for people 
# who are saying 'NO' in MNLogit_new = 2


# Among the people who are neutral with choice of autonomous vehicle the people who
# say that they are neutral with safety of auto vehicles and those
# who are interested in participating carshare_level
# and not participating are significant. This is in comparision to MNL_new=1 or 'Yes'


#For Carshare_Level[T.Interested in participating],for MNL_new=2 or 'Neutral' 
# the odds ratio is e^0.7536 = 2.1246 meaning that the people who are neutral with
#the adoption of self driving vehicles are 2.12 times more likely to adopt
#self driving autonomous vehicles.


#For Carshare_Level[T.Not participating] the odds ratio is
# e^0.5720 = 1.7649 hence the people who are not participating in 
# car share  and have chosen neutral are 1.7649 times favarouble to use
#self driving autonomous vehicles.